---
Domain: 'spog.ai'
baseURL: http://docs.spog.ai
title: spog.ai docs
copyRight: 'spog.ai (c) 2020-2021. All rights reserved.'

params:
  geekdocLogo: spog_logo.png
  company: 'spog.ai'
  domain: 'spog.ai'
  cvdomain: 'spog.ai'
  themeColor: '#0abab5'
  product: 'spog.ai CloudVista SaaS'
  geekdocLegalNotice: https://www.spog.ai/legal
  geekdocPrivacyPolicy: https://www.spog.ai/privacy
